[bans]
multiple-versions = "deny"

# We should always specify version ranges
wildcards = "deny"
allow-wildcard-paths = true

deny = []

skip-tree = [
    { name = "darling" }, # TODO: validator crate must upgrade
    { name = "winnow" },  # TODO: toml crate must upgrade
]

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]
private = { ignore = true }


[sources]
unknown-git = "deny"
unknown-registry = "deny"


[advisories]
yanked = "deny"
unused-ignored-advisory = "deny"

ignore = [
    # proc-macro-error2 (unmaintained)
    # https://rustsec.org/advisories/RUSTSEC-2026-0173
    "RUSTSEC-2026-0173",
]
